application: covert-box
version: 2
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: firenze.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
